[package]
name = "mach_o_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
byteorder = "1.5.0"
crossterm = "0.27.0"
ratatui = "0.26.2"
color-eyre = "0.6.3"